/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import CargarArchivos.Cargar;
import CargarArchivos.FileChooser;
import static Interfaces.Iniciar.gestionApp;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alexa
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        nombreLinaje.setText(gestionApp.getNombreFamilia());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreLinaje = new javax.swing.JLabel();
        cargarNuevo = new javax.swing.JButton();
        verArbol = new javax.swing.JButton();
        buscarPorNombre = new javax.swing.JButton();
        buscarPorTitulo = new javax.swing.JButton();
        verGen = new javax.swing.JButton();
        verAntepasados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Principal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 470, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("Linaje Cargado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        nombreLinaje.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        nombreLinaje.setText("N");
        jPanel1.add(nombreLinaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        cargarNuevo.setText("Cargar Nuevo Linaje");
        cargarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(cargarNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        verArbol.setText("Ver Arbol");
        verArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verArbolActionPerformed(evt);
            }
        });
        jPanel1.add(verArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        buscarPorNombre.setText("Buscar Por Nombre");
        buscarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorNombreActionPerformed(evt);
            }
        });
        jPanel1.add(buscarPorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        buscarPorTitulo.setText("Buscar Por Titulo");
        buscarPorTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorTituloActionPerformed(evt);
            }
        });
        jPanel1.add(buscarPorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        verGen.setText("Ver Generaciones");
        verGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verGenActionPerformed(evt);
            }
        });
        jPanel1.add(verGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        verAntepasados.setText("Ver Antepasados");
        verAntepasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAntepasadosActionPerformed(evt);
            }
        });
        jPanel1.add(verAntepasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarNuevoActionPerformed
        Cargar cargarArchivo = new Cargar();
        FileChooser abrir = new FileChooser(this);

        String ruta = abrir.abrirArchivo();

        try {
            cargarArchivo.cargarArchivo(ruta);
            if (cargarArchivo.getEstructuraArbol() != null) {
                
                
                gestionApp.setArbolGenealogico(cargarArchivo.getEstructuraArbol());
                gestionApp.setTablaPersonas(cargarArchivo.getTablaHash());
                gestionApp.setNombreFamilia(cargarArchivo.getNombreFamilia());
                
                nombreLinaje.setText(gestionApp.getNombreFamilia());

                JOptionPane.showMessageDialog(null, "Se cargo un nuevo linaje");
            } else {
                JOptionPane.showMessageDialog(null, "Hay errores en el JSON");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Iniciar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cargarNuevoActionPerformed

    private void buscarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorNombreActionPerformed
        BuscarNombre v1 = new BuscarNombre();
        this.dispose();
    }//GEN-LAST:event_buscarPorNombreActionPerformed

    private void buscarPorTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorTituloActionPerformed
        BuscarTitulo v2 = new BuscarTitulo();
        this.dispose();
    }//GEN-LAST:event_buscarPorTituloActionPerformed

    private void verGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verGenActionPerformed
        VerGeneraciones v3 = new VerGeneraciones();
        this.dispose();
    }//GEN-LAST:event_verGenActionPerformed

    private void verAntepasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAntepasadosActionPerformed
        VerAntepasados v4 = new VerAntepasados();
        this.dispose();
    }//GEN-LAST:event_verAntepasadosActionPerformed

    private void verArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verArbolActionPerformed
        System.setProperty("org.graphstream.ui", "swing");
        MostrarArbol verArbol = new MostrarArbol(gestionApp.getArbolGenealogico(), this);
        verArbol.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_verArbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarPorNombre;
    private javax.swing.JButton buscarPorTitulo;
    private javax.swing.JButton cargarNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreLinaje;
    private javax.swing.JButton verAntepasados;
    private javax.swing.JButton verArbol;
    private javax.swing.JButton verGen;
    // End of variables declaration//GEN-END:variables
}
